#pragma once

#include <arduino.h>

#define WHEEL_COUNT 4

#define UPDATE_FREQUENCY 500.0;

#define LED_PIN 13

#define BACK_LEFT_SERVO_DIRECTION_PIN 3
#define BACK_LEFT_SERVO_PULSE_PIN 4
#define BACK_LEFT_ENABLED_PIN 28
#define BACK_LEFT_FAULT_PIN 32

#define BACK_RIGHT_SERVO_DIRECTION_PIN 5
#define BACK_RIGHT_SERVO_PULSE_PIN 6
#define BACK_RIGHT_ENABLED_PIN 29
#define BACK_RIGHT_FAULT_PIN 33

#define FRONT_LEFT_SERVO_DIRECTION_PIN 7
#define FRONT_LEFT_SERVO_PULSE_PIN 8
#define FRONT_LEFT_ENABLED_PIN 30
#define FRONT_LEFT_FAULT_PIN 34

#define FRONT_RIGHT_SERVO_DIRECTION_PIN 9
#define FRONT_RIGHT_SERVO_PULSE_PIN 10
#define FRONT_RIGHT_ENABLED_PIN 31
#define FRONT_RIGHT_FAULT_PIN 35

//General Commands
#define ENABLE_ALL_POWER_STAGES_PIN 11
#define RESET_ALL_FAULTS_PIN 12

//General Returns
#define EMERGENCY_STOP_PIN 23


namespace MecanumRobot{
    void init();
    void loop();
}





